In [31]:
import numpy as np
# 小数点3位まで表示
%precision 3

'%.3f'

In [6]:
data = np.array([9, 2, 3, 4, 10, 6, 7, 8])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8])

In [6]:
data.dtype # Numpyが保持している精度

dtype('int32')

In [9]:
data2 = np.array([0, 1.1, 2.2, 3.3])
data2.dtype

dtype('float64')

In [40]:
print(data + 100)
print(data - 100)
print(data * 100)
print(data / 100)

[109 102 103 104 110 106 107 108]
[-91 -98 -97 -96 -90 -94 -93 -92]
[ 900  200  300  400 1000  600  700  800]
[0.09 0.02 0.03 0.04 0.1  0.06 0.07 0.08]


In [1]:
2 * array([1,2,3]) # エラー

NameError: name 'array' is not defined

In [36]:
print([1,2,3,4,5][2:4:1]) # stepが性の場合、endはindex - 1だから、index2～3が取得される
print([1,2,3,4,5][3:0:-1]) # stepが負の場合、endはindex+1だから、index1～3が逆順で取得される
print([1,2,3,4,5][3::-1]) # stepが負の場合、endを省略すると先頭まで取得（end=0の指定と結果が異なるのに若干違和感…）
print([1,2,3,4,5][::2]) # start,endを省略すると先頭から末尾まで、step単位で取得される
print([1,2,3,4,5][::-2]) # start,endを省略すると先頭から末尾まで、step単位で取得される)

[3, 4]
[4, 3, 2]
[4, 3, 2, 1]
[1, 3, 5]
[5, 3, 1]


In [37]:
data_sort = np.array([1,4,2,3,5])
print(data_sort)
data_sort.sort()
print(data_sort)

[1 4 2 3 5]
[1 2 3 4 5]


In [39]:
data_agg = np.array([1,2,3,4,5,6,7,8,9,10])
print(data_agg.max())
print(data_agg.min())
print(data_agg.sum())
print(data_agg.cumsum())

10
1
55
[ 1  3  6 10 15 21 28 36 45 55]
