In [9]:
import numpy as np
mat = np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.arange(10).reshape(3,3) # エラー

ValueError: cannot reshape array of size 10 into shape (3,3)

In [15]:
# 要素、行、列の抽出
print(mat[1,1])
print(mat[1,2])
print(mat[0,:]) # 行の抽出
print(mat[:,1]) # 列の抽出

4
5
[0 1 2]
[1 4 7]


In [47]:
# 要素内の四則演算
print("mat + 5:\n", mat + 5)
print("\nmat - 5:\n", mat - 5)
print("\nmat * 5:\n", mat * 5)
print("\nmat / 5:\n", mat / 5)
print("\nmat ** 2:\n", mat ** 2)
print("\nmat * mat:\n", mat * mat)
print("\nmat * np.array([1,2,3]):\n", mat * np.array([1,2,3]))

mat + 5:
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]

mat - 5:
 [[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]

mat * 5:
 [[ 0  5 10]
 [15 20 25]
 [30 35 40]]

mat / 5:
 [[0.  0.2 0.4]
 [0.6 0.8 1. ]
 [1.2 1.4 1.6]]

mat ** 2:
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]

mat * mat:
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]

mat * np.array([1,2,3]):
 [[ 0  2  6]
 [ 3  8 15]
 [ 6 14 24]]


In [34]:
# 行列の掛け算
print(np.dot(mat, mat))
print("\n", np.dot(mat, mat[:,1]))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

 [18 54 90]


In [46]:
# ゼロ行列
print(np.zeros((2, 3)))
print(np.zeros((2, 3), dtype = np.int64))
print(np.ones((2, 3), dtype = np.float64))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
